from __future__ import annotations

import os
import sqlite3
from contextlib import contextmanager
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Iterator, Optional
from urllib.parse import urlparse

try:
    import psycopg
    from psycopg.rows import dict_row
except Exception:  # pragma: no cover - optional dependency for SQLite-only setups
    psycopg = None
    dict_row = None

try:
    import streamlit as st
except Exception:  # pragma: no cover - allows non-Streamlit scripts to use SQLite locally
    st = None


APP_DIR = Path(__file__).resolve().parent
DEFAULT_DB_PATH = APP_DIR / "freezers.sqlite3"


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def db_path() -> Path:
    return Path(os.environ.get("FREEZERS_DB_PATH", str(DEFAULT_DB_PATH)))


def _database_url() -> Optional[str]:
    url = os.environ.get("FREEZERS_DATABASE_URL", "").strip()
    if not url and st is not None:
        try:
            url = str(st.secrets.get("FREEZERS_DATABASE_URL", "")).strip()
        except Exception:
            url = ""
    return url or None


def database_label() -> str:
    url = _database_url()
    if not url:
        return str(db_path())
    parsed = urlparse(url)
    host = parsed.hostname or "localhost"
    port = f":{parsed.port}" if parsed.port else ""
    db_name = parsed.path.lstrip("/") or "database"
    return f"postgresql://{host}{port}/{db_name}"


@dataclass(frozen=True)
class _BackendConfig:
    backend: str
    sqlite_path: Path
    postgres_url: Optional[str] = None


def _backend_config(path: Optional[Path] = None) -> _BackendConfig:
    url = _database_url()
    if url:
        return _BackendConfig(backend="postgres", sqlite_path=db_path(), postgres_url=url)
    return _BackendConfig(backend="sqlite", sqlite_path=Path(path or db_path()))


def _translate_sql(sql: str, backend: str) -> str:
    if backend != "postgres":
        return sql
    return sql.replace("?", "%s")


def _split_statements(script: str) -> list[str]:
    return [stmt.strip() for stmt in script.split(";") if stmt.strip()]


class DatabaseConnection:
    def __init__(self, backend: str, conn: Any):
        self.backend = backend
        self._conn = conn

    def execute(self, sql: str, params: Iterable[Any] = ()):
        return self._conn.execute(_translate_sql(sql, self.backend), tuple(params))

    def executescript(self, script: str) -> None:
        if self.backend == "sqlite":
            self._conn.executescript(script)
            return
        for stmt in _split_statements(script):
            self.execute(stmt)

    def commit(self) -> None:
        self._conn.commit()

    def rollback(self) -> None:
        self._conn.rollback()

    def close(self) -> None:
        self._conn.close()


@contextmanager
def connect(path: Optional[Path] = None) -> Iterator[DatabaseConnection]:
    config = _backend_config(path)
    if config.backend == "postgres":
        if psycopg is None:
            raise RuntimeError(
                "Postgres support requires the `psycopg` package. Install `psycopg[binary]` or use SQLite."
            )
        conn = psycopg.connect(config.postgres_url, row_factory=dict_row)
    else:
        conn = sqlite3.connect(str(config.sqlite_path), detect_types=sqlite3.PARSE_DECLTYPES)
        conn.row_factory = sqlite3.Row
        conn.execute("PRAGMA foreign_keys = ON;")

    wrapped = DatabaseConnection(config.backend, conn)
    try:
        yield wrapped
        wrapped.commit()
    finally:
        wrapped.close()


_ID_COLUMN_SQL = {
    "sqlite": "INTEGER PRIMARY KEY AUTOINCREMENT",
    "postgres": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
}


def _schema_sql(backend: str) -> str:
    id_sql = _ID_COLUMN_SQL[backend]
    return f"""
CREATE TABLE IF NOT EXISTS aliquots (
  id {id_sql},
  tube_uid TEXT UNIQUE,
  batch_id TEXT,
  batch_index INTEGER,

  cell_line_name TEXT NOT NULL,
  base_line_1 TEXT,
  base_line_2 TEXT,
  split TEXT,
  date_frozen TEXT,
  date_ln TEXT,
  flask TEXT,
  source TEXT,
  thaw_in TEXT,
  notes TEXT,
  mycoplasma TEXT,

  status TEXT NOT NULL CHECK(status IN ('IN_80','IN_LN','ARCHIVED')),
  tower INTEGER,
  box TEXT,
  position TEXT,

  created_by TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  thawed_by TEXT,
  date_thawed TEXT,
  archived_tower INTEGER,
  archived_box TEXT,
  archived_position TEXT
);

-- Only one tube can occupy an LN slot at a time.
CREATE UNIQUE INDEX IF NOT EXISTS uq_ln_slot
ON aliquots(tower, box, position)
WHERE tower IS NOT NULL AND box IS NOT NULL AND position IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_aliquots_cell_line ON aliquots(cell_line_name);
CREATE INDEX IF NOT EXISTS idx_aliquots_status ON aliquots(status);

CREATE TABLE IF NOT EXISTS events (
  id {id_sql},
  ts TEXT NOT NULL,
  user TEXT,
  action TEXT NOT NULL,
  aliquot_id INTEGER,
  from_status TEXT,
  to_status TEXT,
  from_location TEXT,
  to_location TEXT,
  note TEXT,
  FOREIGN KEY(aliquot_id) REFERENCES aliquots(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS thaw_users (
  name TEXT PRIMARY KEY,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS box_verifications (
  id {id_sql},
  tower INTEGER NOT NULL,
  box TEXT NOT NULL,
  verified_ok INTEGER NOT NULL DEFAULT 1,
  verified_by TEXT,
  verified_date TEXT,
  notes TEXT,
  created_at TEXT NOT NULL
);
""".strip()


def _column_exists_sqlite(conn: DatabaseConnection, table: str, column: str) -> bool:
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return any(str(row[1]) == column for row in rows)


def _column_exists_postgres(conn: DatabaseConnection, table: str, column: str) -> bool:
    rows = conn.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = current_schema()
          AND table_name = ?
        """,
        (table,),
    ).fetchall()
    return any(str(row["column_name"]) == column for row in rows)


def _ensure_column(conn: DatabaseConnection, table: str, column_def: str) -> None:
    column_name = column_def.split()[0]
    if conn.backend == "sqlite":
        if _column_exists_sqlite(conn, table, column_name):
            return
        conn.execute(f"ALTER TABLE {table} ADD COLUMN {column_def}")
        return
    if _column_exists_postgres(conn, table, column_name):
        return
    conn.execute(f"ALTER TABLE {table} ADD COLUMN IF NOT EXISTS {column_def}")


def init_db(path: Optional[Path] = None) -> None:
    with connect(path) as conn:
        conn.executescript(_schema_sql(conn.backend))
        for column in (
            "thawed_by TEXT",
            "date_thawed TEXT",
            "archived_tower INTEGER",
            "archived_box TEXT",
            "archived_position TEXT",
        ):
            _ensure_column(conn, "aliquots", column)
        for column in (
            "verified_ok INTEGER NOT NULL DEFAULT 1",
            "verified_by TEXT",
            "verified_date TEXT",
            "notes TEXT",
            "created_at TEXT NOT NULL",
        ):
            _ensure_column(conn, "box_verifications", column)


def ensure_thaw_user(conn: DatabaseConnection, name: str) -> None:
    cleaned = name.strip()
    if not cleaned:
        return
    if conn.backend == "postgres":
        conn.execute(
            "INSERT INTO thaw_users(name, created_at) VALUES (?, ?) ON CONFLICT (name) DO NOTHING",
            (cleaned, utc_now_iso()),
        )
    else:
        conn.execute(
            "INSERT OR IGNORE INTO thaw_users(name, created_at) VALUES (?, ?)",
            (cleaned, utc_now_iso()),
        )


def fetch_thaw_users(conn: DatabaseConnection) -> list[str]:
    rows = conn.execute("SELECT name FROM thaw_users ORDER BY name").fetchall()
    return [str(row["name"]) for row in rows]


def record_box_verification(
    conn: DatabaseConnection,
    *,
    tower: int,
    box: str,
    verified_ok: bool,
    verified_by: Optional[str],
    verified_date: Optional[str],
    notes: Optional[str] = None,
) -> None:
    conn.execute(
        """
        INSERT INTO box_verifications(tower, box, verified_ok, verified_by, verified_date, notes, created_at)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        (
            tower,
            box.upper(),
            1 if verified_ok else 0,
            verified_by,
            verified_date,
            notes,
            utc_now_iso(),
        ),
    )


def fetch_latest_box_verification(
    conn: DatabaseConnection,
    *,
    tower: int,
    box: str,
) -> Optional[dict[str, Any]]:
    row = conn.execute(
        """
        SELECT *
        FROM box_verifications
        WHERE tower = ? AND box = ?
        ORDER BY id DESC
        LIMIT 1
        """,
        (tower, box.upper()),
    ).fetchone()
    return _row_to_dict(row) if row else None


def clear_inventory_data(conn: DatabaseConnection) -> None:
    if conn.backend == "postgres":
        conn.execute("TRUNCATE TABLE box_verifications, events, aliquots RESTART IDENTITY CASCADE")
        return
    conn.execute("DELETE FROM aliquots")
    conn.execute("DELETE FROM events")
    conn.execute("DELETE FROM box_verifications")


def log_event(
    conn: DatabaseConnection,
    *,
    action: str,
    aliquot_id: Optional[int] = None,
    user: Optional[str] = None,
    from_status: Optional[str] = None,
    to_status: Optional[str] = None,
    from_location: Optional[str] = None,
    to_location: Optional[str] = None,
    note: Optional[str] = None,
) -> None:
    conn.execute(
        """
        INSERT INTO events(ts, user, action, aliquot_id, from_status, to_status, from_location, to_location, note)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (utc_now_iso(), user, action, aliquot_id, from_status, to_status, from_location, to_location, note),
    )


def location_str(tower: Optional[int], box: Optional[str], position: Optional[str]) -> Optional[str]:
    if tower is None or not box or not position:
        return None
    return f"{tower}{box.upper()} {position.upper()}"


def _row_to_dict(row: Any) -> dict[str, Any]:
    if row is None:
        return {}
    if isinstance(row, dict):
        return dict(row)
    try:
        return dict(row)
    except Exception:
        return {k: row[k] for k in row.keys()}


def upsert_aliquot(
    conn: DatabaseConnection,
    *,
    aliquot_id: Optional[int] = None,
    tube_uid: Optional[str] = None,
    batch_id: Optional[str] = None,
    batch_index: Optional[int] = None,
    cell_line_name: str,
    base_line_1: Optional[str] = None,
    base_line_2: Optional[str] = None,
    split: Optional[str] = None,
    date_frozen: Optional[str] = None,
    date_ln: Optional[str] = None,
    flask: Optional[str] = None,
    source: Optional[str] = None,
    thaw_in: Optional[str] = None,
    notes: Optional[str] = None,
    mycoplasma: Optional[str] = None,
    status: str,
    tower: Optional[int] = None,
    box: Optional[str] = None,
    position: Optional[str] = None,
    created_by: Optional[str] = None,
    thawed_by: Optional[str] = None,
    date_thawed: Optional[str] = None,
    archived_tower: Optional[int] = None,
    archived_box: Optional[str] = None,
    archived_position: Optional[str] = None,
) -> int:
    now = utc_now_iso()
    insert_params = (
        tube_uid,
        batch_id,
        batch_index,
        cell_line_name,
        base_line_1,
        base_line_2,
        split,
        date_frozen,
        date_ln,
        flask,
        source,
        thaw_in,
        notes,
        mycoplasma,
        status,
        tower,
        (box.upper() if box else None),
        (position.upper() if position else None),
        thawed_by,
        date_thawed,
        archived_tower,
        (archived_box.upper() if archived_box else None),
        (archived_position.upper() if archived_position else None),
        created_by,
        now,
        now,
    )
    if aliquot_id is None:
        if conn.backend == "postgres":
            cur = conn.execute(
                """
                INSERT INTO aliquots(
                  tube_uid, batch_id, batch_index,
                  cell_line_name, base_line_1, base_line_2, split,
                  date_frozen, date_ln, flask, source, thaw_in, notes, mycoplasma,
                  status, tower, box, position, thawed_by, date_thawed, archived_tower, archived_box, archived_position,
                  created_by, created_at, updated_at
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                RETURNING id
                """,
                insert_params,
            )
            row = cur.fetchone()
            return int(row["id"] if isinstance(row, dict) else row[0])

        cur = conn.execute(
            """
            INSERT INTO aliquots(
              tube_uid, batch_id, batch_index,
              cell_line_name, base_line_1, base_line_2, split,
              date_frozen, date_ln, flask, source, thaw_in, notes, mycoplasma,
              status, tower, box, position, thawed_by, date_thawed, archived_tower, archived_box, archived_position,
              created_by, created_at, updated_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            insert_params,
        )
        return int(cur.lastrowid)

    conn.execute(
        """
        UPDATE aliquots SET
          tube_uid = COALESCE(?, tube_uid),
          batch_id = COALESCE(?, batch_id),
          batch_index = COALESCE(?, batch_index),
          cell_line_name = ?,
          base_line_1 = ?,
          base_line_2 = ?,
          split = ?,
          date_frozen = ?,
          date_ln = ?,
          flask = ?,
          source = ?,
          thaw_in = ?,
          notes = ?,
          mycoplasma = ?,
          status = ?,
          tower = ?,
          box = ?,
          position = ?,
          thawed_by = ?,
          date_thawed = ?,
          archived_tower = ?,
          archived_box = ?,
          archived_position = ?,
          updated_at = ?
        WHERE id = ?
        """,
        (
            tube_uid,
            batch_id,
            batch_index,
            cell_line_name,
            base_line_1,
            base_line_2,
            split,
            date_frozen,
            date_ln,
            flask,
            source,
            thaw_in,
            notes,
            mycoplasma,
            status,
            tower,
            (box.upper() if box else None),
            (position.upper() if position else None),
            thawed_by,
            date_thawed,
            archived_tower,
            (archived_box.upper() if archived_box else None),
            (archived_position.upper() if archived_position else None),
            now,
            aliquot_id,
        ),
    )
    return int(aliquot_id)


def fetch_one(conn: DatabaseConnection, sql: str, params: Iterable[Any] = ()) -> Optional[dict[str, Any]]:
    cur = conn.execute(sql, tuple(params))
    row = cur.fetchone()
    return _row_to_dict(row) if row else None


def fetch_all(conn: DatabaseConnection, sql: str, params: Iterable[Any] = ()) -> list[dict[str, Any]]:
    cur = conn.execute(sql, tuple(params))
    return [_row_to_dict(row) for row in cur.fetchall()]
